Repository jenkinsci/opentelemetry-plugin, pull requests merged in 2023-11, with the labels that each got.

#748 Don't add a null attribute if Jenkins can't resolve Computer host name
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java
Labels: enhancement

#754 chore: refactor code smells
  src/main/java/io/jenkins/plugins/opentelemetry/job/jenkins/GraphListenerAdapterToPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/ConsoleNotes.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/StaplerInstrumentationServletFilter.java
Labels: enhancement

#755 fix: incrementals
  pom.xml
Labels: bug

#762 chore: group dependency updates for opentelemetry
  .github/dependabot.yml
Labels: dependencies
