Repository jenkinsci/opentelemetry-plugin, pull requests merged in 2024-07, with the labels that each got.

#881 fix: Fix No MonitoringAction found when open build log
  src/main/java/io/jenkins/plugins/opentelemetry/OtelUtils.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/OtelEnvironmentContributorService.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogStorageFactory.java
Labels: bug

#876 Reconfigurable MeterProvider to reload the OpenTelemetry configuration
  pom.xml
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetry.java
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryLifecycleListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/computer/MonitoringCloudListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/computer/MonitoringComputerListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/DiskUsageMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/GitHubClientMonitoring.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/JenkinsExecutorMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/JvmMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/OtelJulHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/SCMEventMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/ServletFilterInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringBuildStepListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringRunListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogStorageFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/opentelemetry/OtelContextAwareAbstractRunListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/CloseableMeterProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableMeterProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableOpenTelemetry.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableTracerProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/queue/MonitoringQueueListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/security/AuditingSecurityListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/StaplerInstrumentationServletFilter.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/TraceContextServletFilter.java
  src/test/java/io/jenkins/plugins/opentelemetry/BaseIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/CloseableMeterProviderTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableMeterProviderITTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableMeterProviderTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/servlet/StaplerInstrumentationServletFilterTest.java
Labels: internal

#882 docs: explains how Remote Trace Context Propagation works
  docs/setup-and-configuration.md
Labels: documentation

#886 Fix infinite loop in `ReconfigurableEventLoggingProvider`
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableOpenTelemetry.java
Labels: bug

#887 Move ReconfigurableOpenTelemetry to the Jenkins Otel API Plugin
  pom.xml
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetry.java
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryLifecycleListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryRootAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/GrafanaLogsBackendWithJenkinsVisualization.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiLogStorageRetriever.java
  src/main/java/io/jenkins/plugins/opentelemetry/computer/MonitoringCloudListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/computer/MonitoringComputerListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/DiskUsageMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/GitHubClientMonitoring.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/JenkinsExecutorMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/JvmMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/OtelJulHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/SCMEventMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/ServletFilterInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringRunListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogSenderBuildListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogStorageFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/opentelemetry/OtelContextAwareAbstractRunListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/InstrumentationScope.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableEventLoggerProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableLoggerProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableMeterProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableOpenTelemetry.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableTracerProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/queue/MonitoringQueueListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/security/AuditingSecurityListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/StaplerInstrumentationServletFilter.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/TraceContextServletFilter.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetryTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticStack.java
  src/test/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiLogStorageRetrieverIT.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/log/OtelLocaLogMirroringTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableEventLoggerProviderTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableLoggerProviderTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableMeterProviderITTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableMeterProviderTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ReconfigurableTracerProviderTest.java
Labels: enhancement

#893 fix: update dashboard for Elastic Stack 8.14.2
  src/main/kibana/jenkins-kibana-dashboards-8.10.x.ndjson
  src/main/kibana/jenkins-kibana-dashboards.ndjson
Labels: dependencies

#895 feat: make demo more portable
  demos/Makefile
  demos/config/ansible.dsl
  demos/config/gradle.dsl
  demos/config/import_dashboard.dsl
  demos/config/jenkins.yml
  demos/config/maven.dsl
  demos/config/otel-cli-make.dsl
  demos/config/otel-cli.dsl
  demos/config/otel-collector-config.yaml
  demos/config/plugins.txt
  demos/config/pytest-otel.dsl
  demos/docker-compose.yml
  src/test/resources/elastic-stack.yml
Labels: enhancement

#896 Add trace context propagation in atomic steps
  src/main/java/io/jenkins/plugins/opentelemetry/init/StepExecutionInstrumentationInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/OtelTraceService.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/action/AbstractInvisibleMonitoringAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/action/AbstractMonitoringAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/action/FlowNodeMonitoringAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/action/OtelMonitoringAction.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/init/StepExecutionInstrumentationInitializerTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/SpanContextPropagationSynchronousNonBlockingTestStep.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/SpanContextPropagationSynchronousTestStep.java
Labels: enhancement

#907 JenkinsResourceProvider moved to opentelemetry-api-plugin
  pom.xml
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/resources/JenkinsResourceProvider.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/JenkinsOtelSemanticAttributes.java
  src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider
Labels: chore
