Repository jenkinsci/opentelemetry-plugin, pull requests merged in 2024-12, with the labels that each got.

#993 Better docs on build metrics
  docs/monitoring-metrics.md
Labels: documentation

#999 test: remove plugin installation
  src/test/java/io/jenkins/plugins/opentelemetry/BaseIntegrationTest.java
Labels: bug

#1000 Bump the Maven Wrapper (`mvnw`)
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: internal
