Repository jenkinsci/opentelemetry-plugin, pull requests merged in 2024-01, with the labels that each got.

#774 chore: fix a bunch of warning
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/BearerTokenAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/HeaderAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/NoAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/OtlpAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/GrafanaBackend.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticLogsBackendWithJenkinsVisualization.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticsearchLogStorageRetriever.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/JenkinsCredentialsToApacheHttpCredentialsAdapter.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/action/AbstractMonitoringAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/ConsoleNotes.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/LogsViewHeader.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/util/LineIterator.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/BuildTriggerStepHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/GitStepHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/WithSpanAttributeStep.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginFreestyleIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginMBPIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JobDslIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/log/ConsoleNotesTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/log/OpenTelemetryLogToElasticsearchIT.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/WithSpanAttributeStepTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/ClosingOpenTelemetryTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/remotespan/RemoteSpanDisabledTest.java
Labels: chore

#784 docs: rename security.md
  README.md
  docs/security_obs.md
Labels: documentation

#723 chore: Test Java 21
  Jenkinsfile
Labels: dependencies

#788 feat: enable releases from GitHub
  .github/dependabot.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#785 feat: update dashboard to latest Elastic Stack
  src/main/kibana/jenkins-kibana-dashboards.ndjson
Labels: enhancement

#743 feat: Store step/stage result as attribute on corresponding spans
  docs/job-traces.md
  pom.xml
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/jenkins/AbstractPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/jenkins/GraphListenerAdapterToPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/jenkins/PipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/JenkinsOtelSemanticAttributes.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/StepResultTest.java
Labels: enhancement

#799 fix: use Kibana Dashboard parameters
  src/main/java/io/jenkins/plugins/opentelemetry/backend/ElasticBackend.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticLogsBackend.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticLogsBackendWithJenkinsVisualization.java
Labels: bug
