Repository jenkinsci/opentelemetry-plugin, pull requests merged in 2025-02, with the labels that each got.

#1039 Support Jenkins restart
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/OtelJulHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/ServletFilterInitializer.java
Labels: bug

#1046 fix: `WorkflowRun.getLogFile()` deletes logs
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogStorage.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/log/OtelLocaLogMirroringTest.java
Labels: bug

#1047 chore: remove unused Release Drafter workflow
  .github/workflows/release-drafter.yml
Labels: enhancement, chore

#1048 opentelemetry-resources provided by opentelemetry-api
  pom.xml
Labels: internal
