Repository jenkinsci/opentelemetry-plugin, pull requests merged in 2025-01, with the labels that each got.

#1010 Better OTel SDK config on Jenkins build agents
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetry.java
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/OtelUtils.java
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/BearerTokenAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/HeaderAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/OpenTelemetryConfigurerComputerListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/OpenTelemetryTraceContextPropagatorFileCallableWrapperFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringRunListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/OtelEnvironmentContributorService.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogStorageFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/autoconfigure/ConfigPropertiesUtils.java
  src/main/java/io/jenkins/plugins/opentelemetry/queue/MonitoringQueueListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/ConfigurationKey.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/JenkinsOtelSemanticAttributes.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/OTelEnvironmentVariablesConventions.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/OpenTelemetryMetricsSemanticConventions.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/OpenTelemetryTracesSemanticConventions.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/StaplerInstrumentationServletFilter.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/TraceContextServletFilter.java
  src/test/java/io/jenkins/plugins/opentelemetry/BaseIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/init/StepExecutionInstrumentationInitializerTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/remotespan/RemoteSpanTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/semconv/ConfigurationKeyTest.java
Labels: bug

#1021 Use `otel.metric.export.interval` instead of the no longer used `otel.imr.export.interval`
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/OtelEnvironmentContributorService.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/ConfigurationKey.java
  src/main/resources/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration/config.jelly
  src/main/resources/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration/help-configurationProperties.html
  src/main/resources/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration/help-disabledResourceProviders.html
  src/main/resources/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration/help-exportIntervalMillis.html
  src/main/resources/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration/help-exporterIntervalMillis.html
  src/main/resources/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration/help-exporterTimeoutMillis.html
  src/test/java/io/jenkins/plugins/opentelemetry/BaseIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetryTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/OpenTelemetryConfigurationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/jcasc/ConfigurationAsCodeDefaultTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/jcasc/ConfigurationAsCodeElasticLogsBackendExclusiveTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/jcasc/ConfigurationAsCodeElasticLogsBackendTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/jcasc/ConfigurationAsCodeElasticTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/jcasc/ConfigurationAsCodeJaegerTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/jcasc/ConfigurationAsCodeTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/jcasc/ConfigurationAsCodeZipkinTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/log/OtelLocaLogMirroringTest.java
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc-elastic-backend.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/configuration-as-code-expected.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/configuration-as-code.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/elastic-expected.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/elastic.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/jaeger-expected.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/jaeger.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/zipkin-expected.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/zipkin.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/job/step/jcasc-elastic-backend.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/remotespan/jcasc-elastic-backend.yml
  src/test/resources/io/jenkins/plugins/opentelemetry/remotespan/remote-span-disabled.yml
Labels: bug

#1025 Adopt `@Serial`
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryAttributesAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/CredentialsNotFoundException.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/OpenTelemetryTraceContextPropagatorFileCallableWrapperFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/FlowNodeTraceContext.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogSenderBuildListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/RunTraceContext.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/util/TeeOutputStreamBuildListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/SpanAttribute.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/SpanAttributeStepExecution.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/SpanContextPropagationSynchronousNonBlockingTestStep.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/SpanContextPropagationSynchronousTestStep.java
Labels: internal

#1030 Change `assumeTrue` import so that tests are properly skipped
  src/test/java/io/jenkins/plugins/opentelemetry/rules/CheckIsDockerAvailable.java
Labels: enhancement, internal

#1024 Adopt OTel naming conventions
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetry.java
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticsearchBuildLogsLineIterator.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticsearchFields.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticsearchLogStorageRetriever.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiLogStorageRetriever.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiMetadata.java
  src/main/java/io/jenkins/plugins/opentelemetry/computer/MonitoringCloudListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/computer/MonitoringComputerListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/DiskUsageMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/GitHubClientMonitoring.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/JenkinsExecutorMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/PluginMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/SCMEventMonitoringInitializer.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/OpenTelemetryConfigurerComputerListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/OpenTelemetryTraceContextPropagatorFileCallableWrapperFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringBuildStepListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringRunListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/OtelEnvironmentContributorService.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/OtelTraceService.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/action/RunPhaseMonitoringAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/ConsoleNotes.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/FlowNodeTraceContext.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogOutputStream.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogSenderBuildListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogStorage.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/RunTraceContext.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/runhandler/DefaultRunHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/runhandler/JobDslRunHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/runhandler/MatrixRunHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/AbstractGitStepHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/BuildTriggerStepHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/GitCheckoutStepHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/GlobalOpenTelemetrySdk.java
  src/main/java/io/jenkins/plugins/opentelemetry/queue/MonitoringQueueListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/security/AuditingSecurityListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/ExtendedJenkinsAttributes.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/GitHubAttributes.java
  src/main/java/io/jenkins/plugins/opentelemetry/semconv/JenkinsMetrics.java
  src/main/java/io/jenkins/plugins/opentelemetry/servlet/StaplerInstrumentationServletFilter.java
  src/test/java/io/jenkins/plugins/opentelemetry/BaseIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetryTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginFreestyleIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginMBPIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginMatrixIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/MonitoringActionTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/GitStepHandlerTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/SetSpanAttributesStepTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/StepResultTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/WithSpanAttributeStepTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/WithSpanAttributesStepTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/remotespan/RemoteSpanDisabledTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/remotespan/RemoteSpanTest.java
  src/test/resources/io/jenkins/plugins/opentelemetry/jcasc/zipkin.yml
Labels: java, internal
