Repository jenkinsci/opentelemetry-plugin, pull requests merged in 2025-04, with the labels that each got.

#1074 fix: docs image
  docs/setup-and-configuration.md
Labels: documentation

#1079 Remove calls to the deprecated OTel Events Logger API
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsControllerOpenTelemetry.java
Labels: bug

#1078 Bump build dependencies
  pom.xml
Labels: dependencies

#1082 fix: demo
  .editorconfig
  demos/docker-compose.yml
  src/test/resources/docker-compose.yml
Labels: internal

#1098 fix: reimplement http authentification
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticLogsBackendWithJenkinsVisualization.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticsearchLogStorageRetriever.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/GrafanaLogsBackendWithJenkinsVisualization.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiBuildLogsLineIterator.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiLogStorageRetriever.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/HttpAuthHeaderFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/JenkinsCredentialsToApacheHttpCredentialsAdapter.java
  src/test/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiBuildLogsLineIteratorIT.java
  src/test/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiBuildLogsLineIteratorTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/backend/grafana/LokiLogStorageRetrieverIT.java
  src/test/java/io/jenkins/plugins/opentelemetry/jenkins/HttpAuthHeaderFactoryTest.java
Labels: bug

#1099 fix: warnings cleanup
  src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java
  src/main/java/io/jenkins/plugins/opentelemetry/OpenTelemetryAttributesAction.java
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/BearerTokenAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/authentication/HeaderAuthentication.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticLogsBackend.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticsearchLogStorageRetriever.java
  src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/GrafanaLogsBackend.java
  src/main/java/io/jenkins/plugins/opentelemetry/init/OtelJulHandler.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/HttpAuthHeaderFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/OpenTelemetryConfigurerComputerListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/jenkins/OpenTelemetryTraceContextPropagatorFileCallableWrapperFactory.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/OtelEnvironmentContributor.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/jenkins/GraphListenerAdapterToPipelineListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/OtelLogStorage.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/log/util/TeeOutputStream.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/opentelemetry/OtelContextAwareAbstractRunListener.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/SetSpanAttributesStep.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/WithSpanAttributeStep.java
  src/main/java/io/jenkins/plugins/opentelemetry/job/step/WithSpanAttributesStep.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginMatrixIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/JenkinsOtelPluginMavenIntegrationTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/backend/elastic/ElasticsearchBackendITTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/job/step/SpanContextPropagationSynchronousNonBlockingTestStep.java
  src/test/java/io/jenkins/plugins/opentelemetry/opentelemetry/GlobalOpenTelemetrySdkTest.java
  src/test/java/io/jenkins/plugins/opentelemetry/semconv/ConfigurationKeyTest.java
Labels: internal
